# Generated by Django 4.1.2 on 2022-10-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webzine', '0004_webzinecontents_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webzinecontents',
            name='contents',
            field=models.TextField(null=True),
        ),
    ]
